# Tempo configuration file largely inspired by the following example:
# https://github.com/grafana/tempo/blob/main/example/docker-compose/shared/tempo.yaml
# Some parts that are not essential for the demo were removed.
# See doc for more details: https://grafana.com/docs/tempo/latest/configuration/
stream_over_http_enabled: true
server:
  http_listen_port: 3200
  log_level: info

distributor:
  receivers:                           # this configuration will listen on all ports and protocols that tempo is capable of.
    otlp:
      protocols:
        http:
        grpc:

storage:
  trace:
    backend: local                     # backend configuration to use
    wal:
      path: /tmp/tempo/wal             # where to store the wal locally
    local:
      path: /tmp/tempo/blocks