global:
  scrape_interval: 1s
  external_labels:
    monitor: 'global-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'products-service'
    scrape_interval: 1s
    static_configs:
      - targets: ['products-service:9094']