# Docker Compose responsible for the starting monitoring backend services as a show case for
# OpenTelemetry direct connection.
# In particular, the following services are started:
# - Prometheus - for metrics collection and storage;
# - Jaeger - for traces collection and storage;
#
# Run with the following command: docker-compose -f docker-compose/opentelemetry/prometheus-docker-compose.yml up -d
version: '3.9'

services:

  # Start Jeager for traces storage.
  # UI is available at http://localhost:16686
  # See for more details: https://www.jaegertracing.io/docs/1.53/getting-started/#all-in-one
  jaeger:
    image: jaegertracing/all-in-one:1.53
    container_name: jaeger
    hostname: jaeger
    restart: always
    networks:
      - products
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

  # Start prometheus that will collect metrics from the product service directly.
  # The UI is available at http://localhost:9090
  prometheus-direct:
    image: prom/prometheus:v2.33.3
    container_name: prometheus
    hostname: prometheus
    restart: always
    volumes:
      - ./mount/prometheus-direct.yml:/etc/prometheus/prometheus.yml
    networks:
      - products
    ports:
      - "9090:9090"

  # Start prometheus that will collect metrics from the OTEL collector.
  # The UI is available at http://localhost:9090
  prometheus-collector:
    image: prom/prometheus:v2.33.3
    container_name: prometheus
    hostname: prometheus
    restart: always
    volumes:
      - ./mount/prometheus-collector.yml:/etc/prometheus/prometheus.yml
    networks:
      - products
    ports:
      - "9090:9090"

networks:
  products:
