# Docker Compose responsible for the starting Grafana stack of monitoring backend services as a showcase for
# OpenTelemetry collector connection.
# In particular, the following services are started:
# - ??? - for metrics collection and storage;
# - Tempo - for traces collection and storage. See for more details: https://grafana.com/oss/tempo
version: '3.9'

services:

  # Start Grafana Tempo to receive and store tracing data
  # This configuration is largely inspired by the Tempo local storage docker-compose example:
  # https://github.com/grafana/tempo/blob/main/example/docker-compose/local/docker-compose.yaml
  # It uses a fixed version of the Tempo image at the most recent commit at the time of writing.
  tempo:
    image: grafana/tempo:2.3.1
    command: [ "-config.file=/etc/grafana-tempo.yaml" ]
    restart: always
    volumes:
      - ./mount/grafana-tempo.yaml:/etc/grafana-tempo.yaml
    ports:
      - "5317:4317"  # otlp grpc
      - "5318:4318"  # otlp http
      - "3200:3200"  # tempo

  # Starts Grafana Mimir to receive and store metrics data.
  # This configuration is largely inspired by the Mimir "Get Started" documentation:
  # https://grafana.com/docs/mimir/latest/get-started/
  # It uses a fixed version of the Tempo image at the most recent commit at the time of writing.
  mimir:
    image: grafana/mimir:2.11.0
    command: [ "-config.file=/etc/grafana-mimir.yaml" ]
    restart: always
    volumes:
      - ./mount/grafana-mimir.yaml:/etc/grafana-mimir.yaml
    ports:
      - "9009:9009" # Mimir port

  # Start grafana agent to receive data from OpenTelemetry collector.
  # See for more details: https://grafana.com/docs/agent/latest/static/set-up/install/install-agent-docker/
  grafana-agent:
    image: grafana/agent:v0.39.2
    restart: always
    environment:
      - AGENT_MODE=flow
    volumes:
      - ./mount/grafana-agent.river:/etc/agent/grafana-agent.river
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/agent/grafana-agent.river
    ports:
      - "6317:4317"  # OTLP grpc
      - "6318:4318"  # OTLP http
      - "12345:12345" # UI

  grafana:
    image: grafana/grafana:10.2.2
    restart: always
    volumes:
      - ./mount/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor traceQLStreaming metricsSummary
    ports:
      - "3000:3000"