# Docker Compose responsible for the starting monitoring backend services as a show case for
# OpenTelemetry direct connection.
# In particular, the following services are started:
# - Prometheus - for metrics collection and storage;
# - Jaeger - for traces collection and storage;
#
# Run with the following command: docker-compose -f docker-compose/opentelemetry/prometheus-docker-compose.yml up -d
version: '3.9'

services:

  # Start Jeager for traces storage.
  # UI is available at http://localhost:16686
  # See for more details: https://www.jaegertracing.io/docs/1.6/getting-started/
  jaeger:
    image: jaegertracing/all-in-one:1.23
    container_name: jaeger
    hostname: jaeger
    restart: always
    networks:
      - products
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

  # Start prometheus.
  # UI is available at http://localhost:9090
  prometheus:
    build: docker/prometheus/.
    container_name: prometheus
    hostname: prometheus
    restart: always
    networks:
      - products
    ports:
      - "9090:9090"

networks:
  products:
