# Docker Compose responsible for starting the storage services required by the product service.
# In particular, it starts a PostgreSQL database and an Elasticsearch instance.
version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    hostname: postgres
    restart: always
    networks:
      - products
    environment:
      POSTGRES_DB: "products"
      POSTGRES_USER: products_user
      POSTGRES_PASSWORD: products_password
    ports:
      - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    hostname: elasticsearch
    restart: always
    networks:
      - products
    environment:
      - "xpack.security.enabled=false"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"

networks:
  products:
