# Docker compose to demonstrate publishing of metrics and traces to monitoring backend though OTEL collector.
# Run with the following command: docker-compose -f docker-compose/setup-otel-collector-publishing-extended-filter.yaml up -d
version: "3.9"
services:
  elasticsearch:
    extends:
      file: common-environment.yaml
      service: elasticsearch
    hostname: elasticsearch
    networks:
      - products

  postgres:
    extends:
      file: common-environment.yaml
      service: postgres
    hostname: postgres
    networks:
      - products

  jaeger:
    extends:
      file: common-monitoring-prometheus-jeager.yml
      service: jaeger
    hostname: jaeger
    networks:
      - products

  prometheus:
    extends:
      file: common-monitoring-prometheus-jeager.yml
      service: prometheus-collector
    hostname: prometheus
    networks:
      - products

  grafana-agent:
    extends:
      file: common-monitoring-grafana-stack.yaml
      service: grafana-agent
    hostname: grafana-agent
    networks:
      - products

  tempo:
    extends:
      file: common-monitoring-grafana-stack.yaml
      service: tempo
    hostname: tempo
    networks:
      - products

  mimir:
    extends:
      file: common-monitoring-grafana-stack.yaml
      service: mimir
    hostname: mimir
    networks:
      - products

  loki:
    extends:
      file: common-monitoring-grafana-stack.yaml
      service: loki
    hostname: loki
    networks:
      - products

  grafana:
    extends:
      file: common-monitoring-grafana-stack.yaml
      service: grafana
    hostname: grafana
    networks:
      - products

  products-service:
    extends:
      file: common-products-service.yaml
      service: products-service
    depends_on:
      - postgres
      - elasticsearch
    hostname: products-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/products
      - SPRING_DATASOURCE_USERNAME=products_user
      - SPRING_DATASOURCE_PASSWORD=products_password
      - SPRING_ELASTICSEARCH_REST_URI=elasticsearch:9200
      - OTEL_SERVICE_NAME=products_service
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4418
    networks:
      - products

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.93.0
    hostname: otel-collector
    volumes:
      - ./mount/otel-collector-config-prometheus-jaeger-grafana-process.yaml:/etc/otelcol-contrib/config.yaml
    networks:
      - products

networks:
  products:
